version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql             # Tên service mysql trong compose
      PMA_PORT: 3306
      PMA_USER: user              # Bạn có thể dùng 'user' hoặc 'root'
      PMA_PASSWORD: password      # Tương ứng với MYSQL_PASSWORD bên trên
    ports:
      - "8081:80"
    restart: always

volumes:
  mysql-data:
