version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sapassword     # Mật khẩu cho user root
      MYSQL_DATABASE: testdocker          # Tên database cần tạo
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
