# Sử dụng image Node.js chính thức
FROM node:18

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép file package.json vào container
COPY package.json .

# Cài đặt thư viện
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Mở port 3000
EXPOSE 3000

# Lệnh chạy ứng dụng
CMD ["npm", "start"]
